services:
  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Sobrescribir para Docker (dentro de la red)
      - MONGO_DEMO_URL=mongodb://mongodb:27017

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
  mongodb_config: